### PR TITLE
Mecademics Docs

### PR DESCRIPTION
**Pull request by jingxiangmo**
Documentation for Flojoy Robotics

### CODE REVIEW

**Comment by TheBigSasha** [comment]
Are you sure we want the video placeholder in rn? Otherwise LGTM

**Comment by jingxiangmo** [comment]
We are waiting for the video right now

**Review by TheBigSasha — DISMISSED** [review]

**Comment by TheBigSasha** [comment]
@jingxiangmo  please review, I had to make some non trivial changes to catch this up with main, please verify I didn't break anything you did. If I didn't, looks good to me. I am not sure why it says block completeness fails, I ran just sync and committed all before pushing.

**Comment by jingxiangmo** [comment]
Video doesn't work in preview. Would it work in main?
image

**Pull request merged**
